apiVersion: v1
kind: ServiceAccount
metadata:
  name: semantic-search-sa
  namespace: semantic-search
  annotations:
    azure.workload.identity/client-id: "32c9887d-35ad-49c7-86db-0e980c4fa7a7"
  labels:
    azure.workload.identity/use: "true"
